# --- Font Settings ---
font_family      MesloLGS NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# This helps Kitty render those p10k symbols correctly
narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1

# --- Window Look ---
window_padding_width 10
background_opacity 0.95

# --- Theme ---
include catppuccin.conf
