font_family      FiraMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 FiraMono Nerd Font
symbol_map U+E000-U+F8FF FiraMono Nerd Font

window_padding_width 10
background_opacity 0.95
include catppuccin.conf

term xterm-kitty
